apiVersion: v1
kind: Service
metadata:
  name: mcommandes
spec:
  selector:
    app: microservice-commandes
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandes-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-commandes
  template:
    metadata:
      labels:
        app: microservice-commandes
    spec:
      containers:
        - name: microservice-commandes
          image: elganiesta/mcommandes:7
          ports:
            - name: http
              containerPort: 9002
